### ISSUE TITLE
Create a "404" page

### ISSUE THREAD

**Issue by captbaritone** [divad12/vim-awesome#101]
Currently we just show an empty page for URLs that we don't recognize.

![screen shot 2016-03-21 at 12 47 07 pm](https://cloud.githubusercontent.com/assets/162735/13926513/0d008ad8-ef63-11e5-956f-8bf319c09ca8.png)

**Comment by denisinla** [comment]
+1

**Comment by captbaritone** [comment]
@denisinla I don't have any particular idea other than it will probably be the nav bar, the footer and some 404 message. I think getting the js app to render any kind of special 404 view would be worth merging. From there we can look at improving the design.

**Comment by denisinla** [comment]
@captbaritone Added the 404 view with pre-existing styles. Let me know if this will work.

Thanks!
