### ISSUE TITLE
vim-addon-mw-utils listed as having over 3000 users

### ISSUE THREAD

**Issue by dkns** [divad12/vim-awesome#108]
http://vimawesome.com/plugin/vim-addon-mw-utils

Looking at github (https://github.com/marcweber/vim-addon-mw-utils) this addon has 70 stars, no readme and was updated last time 4 years ago. I have some doubts that it's used by over 3000 people.

**Comment by captbaritone** [comment]
@dkns Very suspicious indeed. Thanks for the report, I'll look into it.

**Comment by captbaritone** [comment]
From my investigation, I think it might actually just be that popular:

https://github.com/search?q=MarcWeber%2Fvim-addon-mw-utils&type=Code&utf8=%E2%9C%93

Here's a selection from the list of dotfiles that include it:

```
...
marsanatta/dotfiles
ncarlier/dotfiles
otaviocc/vim-config
pahgawk/dotfiles
leotomas/dotfiles-that-fly
guhehehe/my-dotfiles
jacobbrandt/dotfiles
eliasdorneles/dotfiles
thuetz/vim-files
rookiepig/dotfiles
daure/vim-config
notWorthy/dotfiles
laoguo1986/myvim
zhongchen/dotfile
xnutsive/dotfiles
gnperdue/VimConfiguration
duijf/dotfiles
bdvholmes/dotfiles
honahursey/dotfiles
dmarquant/dotfiles
cnliusen/vimrc
travcunn/dotfiles
HaraldWeber/dotfiles
mugukamil/dotfiles
savruk/dotfiles
obcode/dotfiles
tvandemeer/dotfiles
duracrisis/my-vimrc
lukeberry99/dotfiles
yko/dotfiles
marjinal1st/dotfiles
joshukraine/dotfiles
coneagoe/vim_config
starwing/vimrc
si-mikey/dotfiles
John-Lin/dotfiles
eenagy/dotfiles
kirfnv/dotfiles
alanbriolat/dotfiles
sinakarimi/vimrc
droneru/dotfiles
...
```

I spot checked a few of these, and they all seem to reference the plugin.

**Comment by dkns** [comment]
Huh. Well, you learn something new every day!
