### ISSUE TITLE
web vimawesome.com can't load detail of plugin

### ISSUE THREAD

**Issue by puterakahfi** [divad12/vim-awesome#120]
Hi all, 
I don't know where to report issues about the website functionality,
please deleted this one if i post in wrong place.

I found an issue when click detail of plugin, it's always display preloader
I think the problem is the javacript, in console log it's diplay 
Uncaught TypeError: undefined is not a function   /static/build/js/app.js:1

Thanks.
Kahfi

**Comment by yigitozkavci** [comment]
I do get that console error too. There shows this on console: Uncaught TypeError: u.moment is not a function

**Comment by captbaritone** [comment]
Sorry folks. I broke this when I (stupidly) did #119. 

Fixed here: 00e3b1ba1791ad59bda8a6436fc71b8d92d087f0 

We should be back now.

**Comment by captbaritone** [comment]
@puterakahfi To your question, this _is_ the right place to report issues with website functionality. Thanks for reporting the issue. :+1:
