### ISSUE TITLE
Add JavaScript tests

### ISSUE THREAD

**Issue by divad12** [divad12/vim-awesome#3]

**Comment by captbaritone** [comment]
@freddyrangel If you could help get us pointed in the right direction with this one, that would be hugely helpful. Even just getting the test framework and a single test which we could use as a model.

**Comment by spicyj** [comment]
What sorts of things do you want to test @captbaritone?

**Comment by captbaritone** [comment]
@spicyj I accidentally demonstrated a JS test use-case last night: https://github.com/divad12/vim-awesome/issues/120 (Obviously I still should have loaded one of each type of view after I deployed, but we'll ignore that for now...)

A baseline set of tests that assert that each React class renders would be a good start.
