### ISSUE TITLE
Scrape vim-plug managed plugins

### ISSUE THREAD

**Issue by divad12** [divad12/vim-awesome#41]
[This configuration file](https://github.com/mikker/dotfiles/blob/4526f60978a354251b3bea516408491e08c69c93/vim/plugins.vim) contains plugins managed by https://github.com/junegunn/vim-plug. Scrape them like we do Vundle-, Pathogen-, and NeoBundle-managed plugins

**Comment by balaclark** [comment]
This would good, vim-plug is quite popular now.
