### ISSUE TITLE
Stats data is not updated

### ISSUE THREAD

**Issue by morhetz** [divad12/vim-awesome#61]
I'm pretty sure stats data is not updated at all.
E.g. [syntastic page](http://vimawesome.com/plugin/syntastic) counts 3811 stars, while that's actually 4450 on [github page](https://github.com/scrooloose/syntastic)

**Comment by divad12** [comment]
They're not! The scraper has been broken for quite a few months now... :(

I'm going to try to find some time this weekend to fix that. Apologies for the lack of maintenance here.

**Comment by captbaritone** [comment]
This seems to be fixed, at least in this one plugin's case.
