### ISSUE TITLE
FR: Sorting?

### ISSUE THREAD

**Issue by gerroon** [divad12/vim-awesome#63]
Hi

This is great, thanksfor the awesome work. Is it possible to have basic sorts like based on date, update, name, popularity etc?

thanks

**Comment by divad12** [comment]
Hi, thanks for the compliments!

There's an issue out to sort by newest here: https://github.com/divad12/vim-awesome/issues/13

The current sorting is by popularity already (# of users of a plugin). Maybe that could be made clearer if we have a sorting UI.
