### ISSUE TITLE
Powerline plugin is listed more than once

### ISSUE THREAD

**Issue by dkns** [divad12/vim-awesome#64]
Search for powerline. You'll find few different version although they all point to same github repository (powerline/powerline), e.g.

http://vimawesome.com/plugin/powerline-red
http://vimawesome.com/plugin/powerline-back-to-december
http://vimawesome.com/plugin/powerline-love-story

Same thing with powerline fonts:
http://vimawesome.com/plugin/fonts-if-this-was-a-movie
http://vimawesome.com/plugin/fonts-all-too-well
http://vimawesome.com/plugin/fonts-shouldve-said-no

**Comment by captbaritone** [comment]
Looks like this is due to the fact that we were treating GitHub owner/repo names as case sensitive, when GitHub urls are case insensitive. I'm working on a fix in pull request #80.

**Comment by captbaritone** [comment]
Closing as duplicate of #64.

**Comment by danielcompton** [comment]
This issue is #64? Not sure if it should be a dupe of itself :) ?

**Comment by captbaritone** [comment]
@danielcompton Thanks for catching that brain fart!

**Comment by captbaritone** [comment]
Fixed via https://github.com/divad12/vim-awesome/pull/80 :clap:

Please take a look at the site and feel free to comment here is you see anything screwy.
