### ISSUE TITLE
API consumption in vim-bootstrap.com

### ISSUE THREAD

**Issue by avelino** [divad12/vim-awesome#65]
Hey guys, we are evolving the vim-bootstrap.com and wanted to ask permission to consume the API to you.
Don't be a real-time consumption, we have a process that consumes the API of X in X time (1 time per day) generating a local file for consumption of vim-bootstrap.

See the consumer code: https://github.com/avelino/vim-bootstrap/blob/7fe40d53a75d97e5609f178b4d70ccc7ae1f8016/bin/awesomevim.py

**Comment by captbaritone** [comment]
:+1:

**Comment by divad12** [comment]
Sorry for the late reply, but API consumption is totally cool. :)

http://vim-bootstrap.com/ looks awesome. Good luck and have fun!

**Comment by avelino** [comment]
Thanks...
