### ISSUE TITLE
page 5 is full of powerline

### ISSUE THREAD

**Issue by oinirio** [divad12/vim-awesome#68]
Title explains it good

**Comment by captbaritone** [comment]
URLS are interesting:

* http://vimawesome.com/plugin/powerline-safe-and-sound
* http://vimawesome.com/plugin/powerline-the-story-of-us
* http://vimawesome.com/plugin/powerline-ours
* http://vimawesome.com/plugin/powerline-enchanted
* http://vimawesome.com/plugin/powerline-everything-has-changed
* http://vimawesome.com/plugin/powerline-treacherous
* http://vimawesome.com/plugin/powerline-mine
* http://vimawesome.com/plugin/powerline-forever-and-always

**Comment by dkns** [comment]
Also reported here: #64

**Comment by captbaritone** [comment]
Closing as a duplicate of #64.
