### ISSUE TITLE
DataBase dump missing

### ISSUE THREAD

**Issue by mkuts12** [divad12/vim-awesome#70]
It seems as if the DB dump is not in the link. 
could you please fix the link?
thanks!

**Comment by mkomigor** [comment]
+1

**Comment by captbaritone** [comment]
I believe this was fixed in https://github.com/divad12/vim-awesome/commit/70aeda0ca77f63147d2e5924a393262867b2e76e. Feel free to re-open if you are experiencing issues accessing the database dump.
