### ISSUE TITLE
Should the CtrlP page link to the active Github fork instead?

### ISSUE THREAD

**Issue by i-give-up** [divad12/vim-awesome#73]
[The original repo](https://github.com/kien/ctrlp.vim) hasn't had any commits since more than 2 years ago.

In comparison, [the ctrpvim/ctrlp.vim fork](https://github.com/ctrlpvim/ctrlp.vim) is still actively maintained and is accepting pull requests. Word is that [this fork has the blessing of the CtrlP author](https://github.com/ctrlpvim/ctrlp.vim/issues/128#issuecomment-137352888) but there hasn't been any official word from the author himself yet, nor has he edited the original repo to point people to the fork. 

In any case, I think [the CtrlP page](http://vimawesome.com/plugin/ctrlp-vim-state-of-grace) should link to the fork instead of the dormant original repo so that issues and pull requests can be handled.

**Comment by Delapouite** [comment]
Absolutely. This is a much needed redirection,

**Comment by captbaritone** [comment]
Can anyone think of a general case way to handle this sort of issue? I agree that we should be referencing the fork, but I hesitate to handle this case manually. While this case seems quite clear-cut, in general I don't think this project should be in the business of manually deciding which fork to prefer.

**Comment by divad12** [comment]
+1 @captbaritone

**Comment by captbaritone** [comment]
I've thought about this a bit more, and I think it's probably outside the scope of this project. Our goal is to aggregate the plugins that people are __actually using__. The truth is, the deprecated version is still quite popular. As people move away from the deprecated version that should be reflected in our numbers, and eventually the maintained version will bubble to the top (we hope!).

While we don't redirect, we do show the README, which prominently displays a note that it's deprecated, and gives a link to the maintained version.

I'm going to close this issue, but if somebody wants to make an argument against the above point, I'd be happy to consider reopening the issue.

Thanks everyone for your input!

**Comment by divad12** [comment]
That all sounds good to me, thanks @captbaritone for the thoughts and reasoning!
