### ISSUE TITLE
Can't click links near to the top of readmes

### ISSUE THREAD

**Issue by captbaritone** [divad12/vim-awesome#77]
The padding of `.plugin-page .install .content-column` plus the `height: 100%;` is such that is overhangs its parent and overlaps the very top of the readme text. This renders links near the top unclickable.

![screen shot 2016-02-09 at 9 55 41 am](https://cloud.githubusercontent.com/assets/162735/12925484/5e3ded66-cf13-11e5-9b6c-9082f81e28e1.png)

**Comment by divad12** [comment]
Good find! The README should actually be beneath the "install from" box, but over the years apparently there's been a regression, although the CSS or HTML has not changed (but browsers have!).

It should actually look like this:

![image](https://cloud.githubusercontent.com/assets/159687/12938396/2cf1ee92-cf68-11e5-9e76-5ab9fa128f14.png)

That's done with a `clear: both`.

**Comment by captbaritone** [comment]
Ah, good to know. Should be fixable.

--
Jordan Eldredge

Please excuse any typos or terseness; this email was sent from a mobile device.
