### ISSUE TITLE
Ussage count for EasyMotion is wrong

### ISSUE THREAD

**Issue by captbaritone** [divad12/vim-awesome#87]
It currently shows that 105,437 people are using EasyMotion, but we only have 82,228 dotfile repositories.

<img width="830" alt="screen shot 2016-03-09 at 7 30 50 am" src="https://cloud.githubusercontent.com/assets/162735/13640301/ea0ac258-e5c8-11e5-998e-2e2061f84262.png">

<img width="959" alt="screen shot 2016-03-09 at 7 31 27 am" src="https://cloud.githubusercontent.com/assets/162735/13640320/06511dea-e5c9-11e5-8a70-f4a14f2675c0.png">

**Comment by captbaritone** [comment]
As of the last deploy, this seems to have correct itself.

**Comment by spicyj** [comment]
Weird.
